SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * 3

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_TURN_ACCELERATION = 2.5
PLAYER_SPEED = 200
PLAYER_ACCELERATE = 1.25
PLAYER_DECELERATE = 1.5

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SCORE_GAIN = 10
SCORE_TIME = 2