SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * 3

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_ROTATION_INCREMENT = 90  # Degrees per second²
PLAYER_MAX_ROTATION_ACCEL = 360  # Maximum rotational acceleration
PLAYER_MAX_SPEED = 10
PLAYER_MAX_REVERSE_SPEED = 200
PLAYER_THRUST = 200
PLAYER_DRAG = 0.1
RAY_DECAY_RATE = 50
RAY_VELOCITY_FACTOR = 0.1

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SCORE_GAIN = 10
SCORE_TIME = 2